plugins {
	//id("dev.kikugie.stonecutter")
	id("fabric-loom") version "1.9.2"
	id("maven-publish")
}

archivesBaseName = property("mod.name")
version = "${property("mod.version")}" + "+" + "${property("mod.version_name")}"
group = property("mod.maven_group")

base {
	archivesName = archivesBaseName
}

dependencies {
	minecraft "com.mojang:minecraft:${property('deps.minecraft')}"
	mappings "net.fabricmc:yarn:${property('deps.yarn_mappings')}:v2"
	modImplementation "net.fabricmc:fabric-loader:${property('deps.fabric_loader')}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${property('deps.fabric_api')}"
}

loom {
	runConfigs.all {
		ideConfigGenerated true // Run configurations are not created for subprojects by default
		runDir "../../run" // Use a shared run folder and just create separate worlds
	}
}

def target = ">=${property("mod.min_target")}- <=${property("mod.max_target")}"

processResources {
	def expandProps = [
			'version': project.version,
			"minecraftVersion": target,
			"javaVersion": project.property("deps.java")
	]

	filesMatching('fabric.mod.json') {
		expand expandProps
	}

	inputs.properties(expandProps)
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = 'UTF-8'

	// Minecraft 1.18 (1.18-pre2) upwards uses Java 17.
	it.options.getRelease().set(project.property("deps.java") as Integer)
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	def java = property("deps.java") == "8" ? JavaVersion.VERSION_1_8 : JavaVersion.VERSION_17

	sourceCompatibility = java
	targetCompatibility = java
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archivesBaseName}"}
	}
}

def collectJars = tasks.register("collectJars", Copy) { copy ->

	def task = tasks.named("remapJar")

	dependsOn(task)

	copy.from task
	copy.into rootProject.buildDir.path + "/libs"
}

// Set up assemble to depend on the collectJars task, so it gets run on build.
assemble {
	dependsOn(collectJars)
}

if (stonecutter.current.isActive) {
	loom {
		runConfigs.client {
			ideConfigGenerated = true
			vmArgs "-Dmixin.debug.export=true"
			runDir "../../run"
		}
	}

	rootProject.tasks.register("buildActive") {
		setGroup "project"

		dependsOn tasks.named("build")
	}
}