# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Information
mod.version=1.0.5
mod.name=namefabric
mod.maven_group=net.notcoded

mod.version_name=[VERSIONED]

mod.min_target=[VERSIONED]
mod.max_target=[VERSIONED]

# Dependencies
# https://fabricmc.net/develop
deps.yarn=[VERSIONED]
deps.fabric_loader=0.15.6
deps.fabric_api=[VERSIONED]
deps.java=[VERSIONED]
