# See latest at https://fabricmc.net/develop/
deps.minecraft=1.20.6
deps.yarn_mappings=1.20.6+build.1
deps.fabric_api=0.98.0+1.20.6
deps.java=17

mod.version_name=1.19+

mod.min_target=1.19
mod.max_target=1.22

publishing.supported_versions=1.19,1.19.1,1.19.2,1.19.3,1.19.4,1.20,1.20.1,1.20.2,1.20.3,1.20.4,1.20.5,1.20.6,1.21,1.21.1,1.21.2,1.21.3,1.21.4,1.21.5
