# See latest at https://fabricmc.net/develop/
deps.minecraft=1.16.5
deps.yarn_mappings=1.16.5+build.10
deps.fabric_api=0.42.0+1.16
deps.java=8

mod.version_name=1.16+

mod.min_target=1.16.5
mod.max_target=1.18.2

publishing.supported_versions=1.16,1.16.1,1.16.2,1.16.3,1.16.4,1.16.5,1.17,1.17.1,1.18,1.18.1,1.18.2